# Generated by Django 5.2.4 on 2025-08-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_table'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='otpcode',
            constraint=models.CheckConstraint(condition=models.Q(('code__range', (1000, 9999))), name='otpcode_check_age'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.CheckConstraint(condition=models.Q(('age__range', (1, 99))), name='otpcode_age_check'),
        ),
    ]
