# Generated by Django 5.2.4 on 2025-07-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SmallIntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
