# Generated by Django 5.2.4 on 2025-08-02 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='otpcode',
            table='otpcode',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
