# Generated by Django 5.2.4 on 2025-08-02 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_otpcode_table_alter_profile_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profile ',
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
