# Generated by Django 5.2.4 on 2025-07-18 12:06

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(upload_to='posts/', validators=[home.models.validate_file_extentions]),
        ),
    ]
