# Generated by Django 5.2.4 on 2025-08-02 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_relation_from_user_alter_relation_to_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='relation',
            table='relation',
        ),
    ]
