# Generated by Django 5.2.4 on 2025-08-29 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_relation_from_user_alter_relation_to_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',)},
        ),
    ]
