# Generated by Django 5.2.4 on 2025-09-01 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
    ]
